GET http://localhost:8080/fire/code/list
Cookie: username-localhost-8888=2|1:0|10:1725074706|23:username-localhost-8888|188:eyJ1c2VybmFtZSI6ICJmNzNjOGVkNDBiMWY0ZTQxOGZmYzUyZDc5NDAxYTc1YSIsICJuYW1lIjogIkFub255bW91cyBLYWxlIiwgImRpc3BsYXlfbmFtZSI6ICJBbm9ueW1vdXMgS2FsZSIsICJpbml0aWFscyI6ICJBSyIsICJjb2xvciI6IG51bGx9|aaa34a8cd46575b7fe9b058df9e8130017a3b193d22e15df1849d02292eb9f15; _xsrf=2|6d5c3a57|883a83e1b1a64acedf38a03a4aea7e7d|1725074707; Admin-Token=eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6ImIzNTUyZGEwLTUxOGUtNGExNS1hZGM4LTljOGIxNDUxNTc0OSJ9.qG163UnYWuFJvrNuXKQGtgZw9v5LBlejzDxBaOCtiMoqQhOX4PMPLwaWfse4R0ki_meSvrzsYiHIJyrw4RC07A
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6ImIzNTUyZGEwLTUxOGUtNGExNS1hZGM4LTljOGIxNDUxNTc0OSJ9.qG163UnYWuFJvrNuXKQGtgZw9v5LBlejzDxBaOCtiMoqQhOX4PMPLwaWfse4R0ki_meSvrzsYiHIJyrw4RC07A
